name: Github Self Hosted Runners Example

env:
  EmployeeName: "Deepak Pradhan"
  Message: "Welcome to the CloudEQ"

on: 
  push: 
    branches: ["main", "master"]

  workflow_dispatch:


jobs:
  demojob1:
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v3

    - name: Run a one-line script 
      run: echo "Hello $EmployeeName $Message"

    - name: Run a multi-line script
      run: |
        echo "Hello $EmployeeName"
        echo $Message

